server:
  port: ${port:9003}
spring:
  application:
    # 注册的服务id
    name: root-service
  cloud:
    nacos:
      discovery:
        username: nacos
        password: nacos
        server-addr: localhost:8848
        # 区分开发 测试 发行组方便测试
        group: dev_group
        namespace: 743cb407-170d-4c67-8d26-044ace52c462
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: test
    url: jdbc:mysql://127.0.0.1:3306/springcloud?characterEncoding=utf-8&useSSL=false
  jackson:
      serialization:
        WRITE_DATES_AS_TIMESTAMPS: false
        FAIL_ON_EMPTY_BEANS: true
      time-zone: UTC
mybatis:
  type-aliases-package: com.ljl.user.domain
  mapper-locations: classpath:mapper/*.xml
#eureka:
#  client:
#    service-url:
#      defaultZone: HTTP://127.0.0.1:10086/eureka
#    register-with-eureka: true
#  instance:
#    ip-address: 127.0.0.1
#    prefer-ip-address: true
#    # 续约时间 心跳
#    lease-renewal-interval-in-seconds: 30
#    # 失效时间
#    lease-expiration-duration-in-seconds: 90
logging:
  level:
    com: info
